import Footer from '@/components/Footer';

export const metadata = {
  title: 'Terms of Service',
  description: 'TrueQR Terms of Service.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-950 text-white flex flex-col">
      <div className="max-w-2xl mx-auto px-4 py-16 flex-1">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-10">Last updated: May 2026</p>

        <div className="space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">
              1. Acceptance of terms
            </h2>
            <p>
              By using TrueQR (trueqr.vercel.app), you agree to these Terms of
              Service. If you do not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">
              2. Free tier
            </h2>
            <p>
              Static QR code generation is free, requires no account, and has
              no usage limits. You may use QR codes generated by TrueQR for any
              lawful purpose, including commercial use, without restriction or
              attribution.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">
              3. Paid subscriptions
            </h2>
            <p>
              Pro and Business plans are billed monthly. You may cancel at any
              time; cancellation takes effect at the end of your current billing
              period. We do not offer refunds for partial months.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">
              4. Prohibited use
            </h2>
            <p>You may not use TrueQR to generate QR codes that:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>Link to malware, phishing sites, or illegal content</li>
              <li>Violate any applicable law or regulation</li>
              <li>Infringe on intellectual property rights of others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">
              5. Disclaimer of warranties
            </h2>
            <p>
              TrueQR is provided &ldquo;as is&rdquo; without warranties of any
              kind. We make no guarantees regarding uptime, accuracy, or
              fitness for a particular purpose. Static QR codes depend solely
              on the destination URL remaining valid — we have no control over
              third-party servers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">
              6. Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by law, Neptune Angels LLC (the
              operator of TrueQR) shall not be liable for any indirect,
              incidental, special, or consequential damages arising from your
              use of this service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">7. Contact</h2>
            <p>
              Questions about these terms? Email us at{' '}
              <a
                href="mailto:legal@trueqr.com"
                className="text-indigo-400 hover:text-indigo-300 underline"
              >
                legal@trueqr.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
